version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cadastro
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3307"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
